add docker compose file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,9 +26,6 @@ jobs:
           push: true
           tags: manishsaraan/node-app:${{ github.run_id }}
 
-      - name: Verify push
-        run: docker pull manishsaraan/node-app:${{ github.run_id }}
-
       - name: Deploy to EC2
         uses: appleboy/ssh-action@master
         with:
@@ -37,16 +34,18 @@ jobs:
           key: ${{secrets.SSH_KEY}}
           script: |
             sudo docker pull manishsaraan/node-app:${{ github.run_id }}
-            sudo docker stop node-app || true
-            sudo docker rm node-app || true
-            sudo docker run -d --name node-app -p 3000:3000 manishsaraan/node-app:${{ github.run_id }}
+            export TAG=${{ github.run_id }}
+            sudo docker-compose up
+          #sudo docker stop node-app || true
+          #sudo docker rm node-app || true
+          #sudo docker run -d --name node-app -p 3000:3000 manishsaraan/node-app:${{ github.run_id }}
 
-            # buildid for tag
-            # sonarquebe
-            # container limit on resource use
-            # docker command main env file
-            # run docker compose in detach mode
-            # setup failover in docker compose
-            # promethius
-            # reverse proxy, nginx 
-            # pass variable in docker compose
+          # buildid for tag
+          # sonarquebe
+          # container limit on resource use
+          # docker command main env file
+          # run docker compose in detach mode
+          # setup failover in docker compose
+          # promethius
+          # reverse proxy, nginx
+          # pass variable in docker compose
